apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  # In production, use Secrets instead of ConfigMap for sensitive data
